# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8667a8ef6f291a14d194d13245ab9568d011d4b11fe80b564a16053a9db0b739183e4c795dc144ea1221a3f0b040284fcd28644e3c42be5f8a831f21d79df97b

test:
  secret_key_base: ddfd092123f3e2c8cbc5ea53cec238fdf1b8787f204f2c8dc68e729eacc545e5926eecab412abd099efb7342156f88adbdcc91013d984c10c310f136cef87102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
